name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Angular dependencies
      run: npm ci

    - name: Build Angular app
      run: npm run build

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Python dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Start Angular server
      run: npm start &
      env:
        CI: true

    - name: Start Python server
      run: |
        cd backend
        python manage.py runserver &
      env:
        CI: true

    - name: Run tests
      run: |
        # Run your tests here
    - name: Deploy to Server
      if: github.ref == 'refs/heads/master'  # Adjust to your production branch
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}  # Ensure this matches your GitHub secret's name
        DEPLOY_SERVER: vps-9f62e310.vps.ovh.net
        DEPLOY_USER: ubuntu
      run: |
      
        ls -l ./frontend/
        echo "$SSH_PRIVATE_KEY"  > private.key
        echo "Checking the length of the SSH_PRIVATE_KEY"
        echo "$SSH_PRIVATE_KEY" | wc -c
        sudo chmod 400 private.key
        sudo apt-get update
        sudo apt-get install -y ssh
        eval "$(ssh-agent -s)"
        ssh-add private.key
        mkdir -p ~/.ssh
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      
        scp -r ./frontend/ ${{ env.DEPLOY_USER }}@${{ env.DEPLOY_SERVER }}:/home/ubuntu/belka-stalowa/frontend
        scp -r ./backend $DEPLOY_USER@$DEPLOY_SERVER:/home/ubuntu/belka-stalowa/backend
