name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Angular dependencies
      run: npm ci

    - name: Build Angular app
      run: npm run build

    - name: List directory after build
      run: ls -lR dist/

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Deploy to Server
      if: github.ref == 'refs/heads/master'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        DEPLOY_SERVER: vps-9f62e310.vps.ovh.net
        DEPLOY_USER: ubuntu
      run: |
        eval "$(ssh-agent -s)"
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        ssh-keyscan -H ${{ env.DEPLOY_SERVER }} >> ~/.ssh/known_hosts

        # Copy files to the server
        scp -r dist/ ${{ env.DEPLOY_USER }}@${{ env.DEPLOY_SERVER }}:/home/ubuntu/belka-stalowa/
        scp -r ./backend ${{ env.DEPLOY_USER }}@${{ env.DEPLOY_SERVER }}:/home/ubuntu/belka-stalowa

    - name: Restart Applications with PM2
      run: |
        ssh ${{ env.DEPLOY_USER }}@${{ env.DEPLOY_SERVER }} << 'EOF'
          cd /home/ubuntu/belka-stalowa/
          
          # Stop and restart the Nginx server to serve the Angular app
          sudo systemctl restart nginx

          # Restart the Flask app
          cd backend
          source venv/bin/activate
          pm2 stop belka-stalowa-backend || true
          pm2 start python3 /home/ubuntu/belka-stalowa/backend/app.py --name belka-stalowa-backend --interpreter python3 --interpreter-args='-m flask run --host=0.0.0.0 --port=5000'
          pm2 save
          EOF
       
      env:
        DEPLOY_SERVER: vps-9f62e310.vps.ovh.net
        DEPLOY_USER: ubuntu
